import { Inter } from "next/font/google";
import "./globals.css";
import Footer from '../components/footer/footer'
import Navbar from '../components/navbar/Navbar'
import { dark } from "@clerk/themes";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider 
    appearance={{
      baseTheme: dark,
    }} >
      <html lang="en">
        <body className={inter.className}>
          {/* <SignedOut>
              <SignInComponent/>
              
          </SignedOut> */}
            {/* <SignedIn> */}
              <Navbar />
              {/* <UserButton /> */}
                {children}
                <Footer />
            {/* </SignedIn> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
